# Server Name
spring.application.name=${CONFIG_SERVER_HOSTNAME}

# Server Port
server.port=${CONFIG_SERVER_PORT}

# Config Server Settings
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config/
