cors.allowed-origins=${FRONTEND_URL}
cors.allowed-methods=${CORS_ALLOWED_METHODS}
cors.allowed-headers=${CORS_ALLOWED_HEADERS}
cors.allow-credentials=${ALLOW_CREDENTIALS}
# Preflight cache duration (seconds) - 600s = 10 minutes
cors.max-age=${CORS_MAX_AGE}

# Eureka configuration
eureka.client.service-url.defaultZone=${EUREKA_SERVER}
eureka.instance.prefer-ip-address=${PREFER_IP_ADDRESS}
eureka.instance.hostname=${GATEWAY_SERVER_HOSTNAME}
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Route configuration

# Auth Service Route
spring.cloud.gateway.server.webflux.routes[0].id=${AUTH_SERVER_HOSTNAME}
spring.cloud.gateway.server.webflux.routes[0].uri=lb://${AUTH_SERVER_HOSTNAME}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=${AUTH_SERVICE_PATH_PREFIX}**
